import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Loja online",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
